<template>
  <div class="flex h-20 items-center justify-center">
    <p
      class="not-sr-only inline-block select-none bg-gradient-to-r from-rpd-pine via-rpd-gold to-rpd-iris bg-clip-text text-center text-sm leading-[1px] text-transparent"
    >
    TnIXCtNIXcTnIxctniXCTnIxCtNixCTniXctNixc
    TNIXctNixctniXCtnIXCtnIXCtNIXCtnIxctnIxc
    TnixcTNIXCtNiXctNIxctnIxCtNiXcTNiXCtniXC
    TNiXCtNiXCtNixCtnIxcTnIXCTnIXcTnIXcTnixc
    TniXCtNIXctNixctNIXcTNiXCtNiXCTNIXctnIXc
    tnIxctNixctnIxCtNiXCTnIxCtNIXctniXCtniXc
    TnIXctNIXCtNixcTnIxCtNiXcTniXCTNiXCtnixC
    TnIXcTNIxctNixctNixCtnIXCtNixCTniXctnIxc
    TNIxCTnIXcTnIXctnIXCtnIxCTnixCtNIxcTniXC
    tNiXCtnIXCTNIxCTniXCtNIxctNIXcTNIXctnIXC
    tnIXcTnIxCTnIxctNIXCtnixctnIXcTNiXCtniXc
    tNIXCtNIxctNIXCtnIxCtniXctniXCtnIXcTNIxc
    tNIxCTniXCTNIxcTnIXCtniXCTnIxctNIxCTNIxC
    TnIxCTNixCTniXcTNIXcTnIXcTnIxCtNIXCtNiXC
    TNiXctnIxCTNIxctnIXctniXCTniXCTNIxcTNIXc
    TNixCtNixcTNIxctniXCtnIXCtniXCtNiXctNixc
    tNIxCTNIxCTniXctNIxcTnIxCTNixcTNIXCTNIXc
    TNixcTNixcTnIxcTniXctNixcTNixCTnIxctnIXc
    TNixcTNiXCtNIXcTnixCtnixctNIXCTniXcTNIxc
    tNixCTNIXcTniXCTnIXCtNiXcTNixctNIXcTNiXc
    tNIXcTniXctNiXctNixCtNixctNiXCtNIxctNiXC
    tNIXCtniXcTNiXCtNIXctNixCtniXCTNixcTNiXc
    TnixcTnixcTnixCtNIXctnixCtNIXCTnIxCtNIXC
    TNiXcTNiXCtNiXctnIxCTnIxCtNiXCtNixCtniXC
    TnIXcTnIXcTNIxCTnIXcTnixCtNixCTnixCTNixC
    TNixcTnIxCTNixcTNIxctNixcTNiXctNiXCTnIxC
    tnIXctNIXctnIXCtnIXctNIXctNiXcTnIXctNixc
    TNiXctnIxCtNIxCTNIXcTNIXcTNixctnIxCTNIXc
    TNixCTnIxctNixCtNiXcTniXCTNixctnIXCtNIxc
    TNiXCTNixcTnIXctnIxctnIXcTNIxcTNixCtnixc
    </p>
  </div>
  <div class="h-20 w-full"></div>
</template>
